### ISSUE TITLE
easy_client() not generating new token file

### ISSUE THREAD

**Issue by brcolli** [alexgolec/tda-api#110]
**Description of Bug**
Calling easy_client(...) returned a _No such file or directory: **path_** when I do not have a previously generated token file. According to the documentation, I believe that this should instead generate a token file, as I currently do not have one.

I installed this using the recommended method of pip and venv. I am also running this through command line.

I can confirm that I have the latest version of Python and this library.

**Code to Reproduce**
```
class StreamSample:

    def __init__(self):

        self.account_id = 'XXXXX'
        self.key = 'XXXXX'
        self.callback_url = 'https://localhost:8080'

        # Setup stream
        self.client = easy_client(api_key=self.key,
                                  redirect_uri=self.callback_url,
                                  token_path='../doc/token.pickle')


if __name__ == '__main__':

    tda.debug.enable_bug_report_logging()

    ofm = StreamSample()
```
**Note:** I have replaced my _account_id_ and _key_ with a fake string.

**Expected Behavior**
I expect to have easy_client() generate a token file for me when I do not already have one.

**Actual Behavior**
_easy_client()_ returns a FileNotFoundError.

**Error/Exception Log, If Applicable**
```
Traceback (most recent call last):
  File "C:/Users/benrc/PycharmProjects/StockTools/src/StreamSample.py", line 44, in <module>
    ofm = StreamSample()
  File "C:/Users/benrc/PycharmProjects/StockTools/src/StreamSample.py", line 18, in __init__
    self.client = easy_client(api_key=self.key,
  File "C:\Users\benrc\PycharmProjects\StockTools\venv\lib\site-packages\tda\auth.py", line 182, in easy_client
    c = client_from_token_file(token_path, api_key)
  File "C:\Users\benrc\PycharmProjects\StockTools\venv\lib\site-packages\tda\auth.py", line 58, in client_from_token_file
    return client_from_access_functions(
  File "C:\Users\benrc\PycharmProjects\StockTools\venv\lib\site-packages\tda\auth.py", line 228, in client_from_access_functions
    token = token_read_func()
  File "C:\Users\benrc\PycharmProjects\StockTools\venv\lib\site-packages\tda\auth.py", line 55, in load
    with open(token_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'token.pickle'

 ### BEGIN REDACTED LOGS ###

[debug.py:162:_enable_bug_report_logging] tda-api version 0.7.1
[auth.py:187:easy_client] Failed to find token file 'token.pickle'
[auth.py:198:easy_client] No webdriver_func set, returning
```

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for help requests. Feel free to join our discord to ask questions:

https://discord.gg/M3vjtHj
