### ISSUE TITLE
tda-api fails to install on OSs that don't support multi-byte characters (minimal OSs can have this problem)

### ISSUE THREAD

**Issue by hmanfarmer** [alexgolec/tda-api#172]
**Description of Bug**
During tda-api install, pyreadline fails to install with error:
` UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1503: ordinal not in range(128)`

This error occurs on OSs that are not configured to understand multibyte characters. For example, the official Docker images for Ubuntu are all minimal installs and they install with character sets that only support single byte characters.

This results in the install process of pyreadline erroring out when it tries to open and read the file "release.py" and encounters an umlaut character in one of the comments of the file. Specifically, this comment:

```
  Contributors to this release:

    - Jörgen Stenarson, maintainer
```

**Code to Reproduce**
On a system running docker.
1. `Docker run -it --name ubuntu_minimal ubuntu:18.04` (after downloading the image, it will run the OS and open a bash prompt)
2. `apt update`
3. `apt install python3.8`
4. `apt install python3-pip`
5. `pip3 install tda-api`

**Expected Behavior**
tda-api should install on minimal OS images.

**Workaround**
From within the Ubuntu image (similar process should be followed on other OSs, but the commands might differ), you need to install utf8 locales that support multibyte characters. Then, you need to inform the OS you want to use one of those locales. These are the commands I ran on my Ubuntu image to get it work:

1. `apt-get update --fix-missing && apt-get install locales`
2. `locale-gen en_US.UTF-8`
3. `export LANG=en_US.UTF-8`
4. `export LC_ALL=en_US.UTF-8`

**Useful Footnotes**

*1*
Excerpt from [Ubuntu's Docker Hub page](https://hub.docker.com/_/ubuntu) explaining that their image only supports single byte character sets out of the box.
```
Given that it is a minimal install of Ubuntu, this image only includes the C, C.UTF-8, and POSIX locales by default. For most uses requiring a UTF-8 locale, C.UTF-8 is likely sufficient (-e LANG=C.UTF-8 or ENV LANG C.UTF-8).

For uses where that is not sufficient, other locales can be installed/generated via the locales package. PostgreSQL has a good example of doing so, copied below:

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
```

*2*
The best explaination of Linux locales and how they are set, installed, and the special case locales (c, posix) that I have found so far was from a unix.stackexchange answer (the answer with the most votes, not the accepted answer):
https://unix.stackexchange.com/a/87763

**Comment by hmanfarmer** [comment]
@alexgolec and I have discussed several solutions to this problem. The simplest of which Alex suggested, which was, only install pyreadline on Mac. Since I can't image Mac ever installing without a multibyte character set, that seems like a fine and relatively simple solution.

But, the question came up. How can we test for this and avoid this problem in the future. To that question, I suggest two changes to the test setup:

1. Add minimal install OSs to the test matrix for the most popular linux distros.
2. on any linux OS, use `export LC_ALL=` and `export LANG=` to change the locale to a locale that doesn't support multibyte characters and then install and run tests.

Change 1 is important because it is likely to catch corner case bugs that pop up with OS where a lot of the common libraries aren't already installed.

Change 2 is important because it directly tests the issue that caused the error (change 1 only tests this indirectly).

**Comment by hmanfarmer** [comment]
Unfortunately, it looks like github workflows do not support minimal OS images. See their page:
https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners

The OSs they provide are chock full of multiple languages, they are the opposite of minimal.

This means that in order to implement my suggestion of `Add minimal install OSs to the test matrix for the most popular linux distros.`, we would probably need to add a new tool to the CI toolchain and a decent amount of complexity. As my brother would say, "I am not sure the juice is worth the squeeze".

**Comment by hmanfarmer** [comment]
It looks like using a docker image inside of the github workflow might not be very difficult:
https://www.petefreitag.com/item/903.cfm

**Comment by hmanfarmer** [comment]
On discord, a user posted the same error, based on his console prompt, it may have actually errored while using a Mac. Which is important because that would mean only installing pyreadline on Mac is not a proper fix. Below is the user's console output during the install (I removed all identifying info from the output):

```
$ pip install tda-api
Collecting tda-api
  Using cached tda_api-1.1.5-py2.py3-none-any.whl (71 kB)
Collecting selenium
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting websockets
  Using cached websockets-8.1-cp36-cp36m-macosx_10_6_intel.whl (66 kB)
Collecting httpx
  Using cached httpx-0.16.1-py3-none-any.whl (65 kB)
Collecting authlib
  Using cached Authlib-0.15.3-py2.py3-none-any.whl (203 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pyreadline
  Using cached pyreadline-2.1.zip (109 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/.../projects/personal/tda/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zt/s3vwc8kx58b8sv7_c1z0tyg40000gp/T/pip-install-00ra_016/pyreadline_e0d93810fe194f578d5dfe0066d58126/setup.py'"'"'; __file__='"'"'/private/var/folders/zt/s3vwc8kx58b8sv7_c1z0tyg40000gp/T/pip-install-00ra_016/pyreadline_e0d93810fe194f578d5dfe0066d58126/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zt/s3vwc8kx58b8sv7_c1z0tyg40000gp/T/pip-pip-egg-info-v8bpgst6
         cwd: /private/var/folders/zt/s3vwc8kx58b8sv7_c1z0tyg40000gp/T/pip-install-00ra_016/pyreadline_e0d93810fe194f578d5dfe0066d58126/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zt/s3vwc8kx58b8sv7_c1z0tyg40000gp/T/pip-install-00ra_016/pyreadline_e0d93810fe194f578d5dfe0066d58126/setup.py", line 21, in <module>
        exec(compile(open('pyreadline/release.py').read(), 'pyreadline/release.py', 'exec'))
      File "/Users/.../projects/personal/tda/bin/../lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1503: ordinal not in range(128)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bc/7c/d724ef1ec3ab2125f38a1d53285745445ec4a8f19b9bb0761b4064316679/pyreadline-2.1.zip#sha256=4530592fc2e85b25b1a9f79664433da09237c1a270e4d78ea5aa3a2c7229e2d1 (from https://pypi.org/simple/pyreadline/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pyreadline-2.0-py3-none-any.whl
Collecting cryptography
  Using cached cryptography-3.4.4-cp36-abi3-macosx_10_10_x86_64.whl (2.0 MB)
Collecting cffi>=1.12
  Using cached cffi-1.14.5-cp36-cp36m-macosx_10_9_x86_64.whl (176 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting sniffio
  Using cached sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting rfc3986[idna2008]<2,>=1.3
  Using cached rfc3986-1.4.0-py2.py3-none-any.whl (31 kB)
Collecting certifi
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting httpcore==0.12.*
  Using cached httpcore-0.12.3-py3-none-any.whl (55 kB)
Collecting h11==0.*
  Using cached h11-0.12.0-py3-none-any.whl (54 kB)
Collecting contextvars>=2.1
  Using cached contextvars-2.4-py3-none-any.whl
Collecting immutables>=0.9
  Using cached immutables-0.15-cp36-cp36m-macosx_10_14_x86_64.whl (53 kB)
Collecting idna
  Using cached idna-3.1-py3-none-any.whl (58 kB)
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting urllib3
  Using cached urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Installing collected packages: immutables, pycparser, contextvars, sniffio, rfc3986, idna, h11, cffi, urllib3, six, httpcore, cryptography, certifi, websockets, selenium, python-dateutil, pyreadline, httpx, authlib, tda-api
Successfully installed authlib-0.15.3 certifi-2020.12.5 cffi-1.14.5 contextvars-2.4 cryptography-3.4.4 h11-0.12.0 httpcore-0.12.3 httpx-0.16.1 idna-3.1 immutables-0.15 pycparser-2.20 pyreadline-2.0 python-dateutil-2.8.1 rfc3986-1.4.0 selenium-3.141.0 six-1.15.0 sniffio-1.2.0 tda-api-1.1.5 urllib3-1.26.3 websockets-8.1
```

**Comment by hmanfarmer** [comment]
@alexgolec I wonder if this library would be a better choice than pyreadline:
https://github.com/ludwigschwardt/python-gnureadline

**Comment by hmanfarmer** [comment]
I finally heard back from the user who ran into the error on his mac OS. His mac is setup for two character sets, Chinese (Mandarin?) and English. He said he uses a keyboard shortcut to switch between the two. He also said the error magically went away and he is not sure what changed. He was pretty confident both the English and Chinese character sets on his machine supported multi-byte characters, and he is confident he installed tda-api while in English mode, because he said he wouldn't have been able to execute the command in Chinese mode.

So... I am not exactly sure how he caused the error and how it he got it to go away.
