### ISSUE TITLE
import auth error

### ISSUE THREAD

**Issue by achillis2** [alexgolec/tda-api#173]
I've successfully installed the tda-api with pip under macOS. However, when I ran import tda, I got an error, see below. I'm using python 3.6 in the virtual env. Can anyone help solve the issue? Thanks! 

(tda4) mypath $ pip install tda-api
Collecting tda-api
  Using cached tda_api-1.1.5-py2.py3-none-any.whl (71 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pyreadline
  Using cached pyreadline-2.1.zip (109 kB)
Collecting httpx
  Using cached httpx-0.16.1-py3-none-any.whl (65 kB)
Collecting authlib
  Using cached Authlib-0.15.3-py2.py3-none-any.whl (203 kB)
Collecting websockets
  Using cached websockets-8.1-cp36-cp36m-macosx_10_6_intel.whl (66 kB)
Collecting selenium
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting cryptography
  Using cached cryptography-3.4.4-cp36-abi3-macosx_10_10_x86_64.whl (2.0 MB)
Collecting cffi>=1.12
  Using cached cffi-1.14.5-cp36-cp36m-macosx_10_9_x86_64.whl (176 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting sniffio
  Using cached sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting httpcore==0.12.*
  Using cached httpcore-0.12.3-py3-none-any.whl (55 kB)
Collecting rfc3986[idna2008]<2,>=1.3
  Using cached rfc3986-1.4.0-py2.py3-none-any.whl (31 kB)
Collecting certifi
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting h11==0.*
  Using cached h11-0.12.0-py3-none-any.whl (54 kB)
Collecting contextvars>=2.1
  Using cached contextvars-2.4-py3-none-any.whl
Collecting immutables>=0.9
  Using cached immutables-0.15-cp36-cp36m-macosx_10_14_x86_64.whl (53 kB)
Collecting idna
  Using cached idna-3.1-py3-none-any.whl (58 kB)
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting urllib3
  Using cached urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Building wheels for collected packages: pyreadline
  Building wheel for pyreadline (setup.py) ... done
  Created wheel for pyreadline: filename=pyreadline-2.1-py3-none-any.whl size=93833 sha256=353f932fb93e2e5d359ec0de6ac29151b80ec956bd83abe4c428a8d6270359a9
  Stored in directory: /Users/dli/Library/Caches/pip/wheels/9c/d5/fa/c30bc1a04703cc6753dc9eea000865417a5d4d70331c77fc2e
Successfully built pyreadline
Installing collected packages: immutables, pycparser, contextvars, sniffio, rfc3986, idna, h11, cffi, urllib3, six, httpcore, cryptography, certifi, websockets, selenium, python-dateutil, pyreadline, httpx, authlib, tda-api
Successfully installed authlib-0.15.3 certifi-2020.12.5 cffi-1.14.5 contextvars-2.4 cryptography-3.4.4 h11-0.12.0 httpcore-0.12.3 httpx-0.16.1 idna-3.1 immutables-0.15 pycparser-2.20 pyreadline-2.1 python-dateutil-2.8.1 rfc3986-1.4.0 selenium-3.141.0 six-1.15.0 sniffio-1.2.0 tda-api-1.1.5 urllib3-1.26.3 websockets-8.1

(tda4) mypath $ python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dli/projects/personal/tda4/tda.py", line 1, in <module>
    from tda import auth, client
ImportError: cannot import name 'auth'
>>>

**Comment by achillis2** [comment]
Never mind. My test code is tda.py which is causing the issue. After renaming the test code filename, I don't have the error anymore.
