### ISSUE TITLE
TypeError: object NoneType can't be used in 'await' expression - Async client, token expired

### ISSUE THREAD

**Issue by meltdown03** [alexgolec/tda-api#245]
**Description of Bug**
With asyncio=True, and streamer running, gets error when trying to run `get_accounts()` method and the token has expired and needs to be updated. 

**Code to Reproduce**
Paste in the code that causes the bug to occur. 
```python
class TDABot():

    def __init__(self, bot, cog, client_id, ref_url=None):
        self.bot = bot
        self.cog = cog
        self.client_id = client_id
        self.ref_url = ref_url

        if not os.path.exists(TOKEN_PATH):
            self.client = easy_client(self.client_id, self.ref_url, TOKEN_PATH,
                                      webdriver_func=lambda: webdriver.Chrome(
                                          ChromeDriverManager().install()),
                                      asyncio=True)
        else:
            self.client = client_from_token_file(
                TOKEN_PATH, self.client_id, asyncio=True)

    async def get_bp(self):
        print("get_bp command running")
        accts = await self.client.get_accounts()
        acct_info = accts.json()
        bp = acct_info[0]['securitiesAccount']['projectedBalances']['availableFunds']
        return bp

    async def read_stream(self, user, account_id):
        try:
            stream_client = StreamClient(
                self.client, account_id=int(account_id))
            await stream_client.login()
            await user.send(f":white_check_mark: TDA account activity streamer started for account id: {account_id}\n\
         (You can now close this DM.)")
            await stream_client.quality_of_service(StreamClient.QOSLevel.EXPRESS)
            await stream_client.account_activity_sub()
            stream_client.add_account_activity_handler(self.get_activity)

            while True:
                await stream_client.handle_message()

        except UnexpectedResponseCode as e:
            await user.send(f":x: Login failed, error: {e} - RESTART BOT AND TRY AGAIN")

        finally:
            await self.client.close_async_session()
```

**Expected Behavior**
Update the token, write the token, return info requested, then continue the program

**Actual Behavior**
errors out, need to run the command again, but then it works.

**Error/Exception Log, If Applicable**
```python
Traceback (most recent call last):
  File "/home/neal/.local/share/virtualenvs/tda-riI-381G/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/neal/tda/dcBot.py", line 81, in start
    await self.tda_client.update_game()
  File "/home/neal/tda/tdaBot.py", line 57, in update_game
    bp = await self.get_bp()
  File "/home/neal/tda/tdaBot.py", line 44, in get_bp
    accts = await self.client.get_accounts()
  File "/home/neal/.local/share/virtualenvs/tda-riI-381G/lib/python3.9/site-packages/tda/client/asynchronous.py", line 21, in _get_request
    resp = await self.session.get(dest, params=params)
  File "/home/neal/.local/share/virtualenvs/tda-riI-381G/lib/python3.9/site-packages/httpx/_client.py", line 1661, in get
    return await self.request(
  File "/home/neal/.local/share/virtualenvs/tda-riI-381G/lib/python3.9/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 90, in request
    await self.ensure_active_token()
  File "/home/neal/.local/share/virtualenvs/tda-riI-381G/lib/python3.9/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 104, in ensure_active_token
    await self.refresh_token(url, refresh_token=refresh_token)
  File "/home/neal/.local/share/virtualenvs/tda-riI-381G/lib/python3.9/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 149, in _refresh_token
    await self.update_token(self.token, refresh_token=refresh_token)
TypeError: object NoneType can't be used in 'await' expression
```

Possible causes:
(https://github.com/lepture/authlib/blob/f17395323555de638eceecf51b535da5b91fcb0a/authlib/integrations/httpx_client/oauth2_client.py#L162)
calls this function of the library when the token is updated:
(https://github.com/alexgolec/tda-api/blob/b640f1f677249d8f127b7cf2de13dc55216c410e/tda/auth.py#L26:L32)

**Comment by alexgolec** [comment]
Reopening because it turns out that submitting code without tests is a recipe for buggy code...
