### ISSUE TITLE
chromedriver issues

### ISSUE THREAD

**Issue by spitzbubchen** [alexgolec/tda-api#60]
Installing tda-api on Ubuntu I am running into this issue:

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    c = auth.client_from_token_file(token_path, api_key)
  File "/home/rod/Projects/tda/venv/lib/python3.6/site-packages/tda/auth.py", line 59, in client_from_token_file
    api_key, load, __token_updater(token_path))
  File "/home/rod/Projects/tda/venv/lib/python3.6/site-packages/tda/auth.py", line 228, in client_from_access_functions
    token = token_read_func()
  File "/home/rod/Projects/tda/venv/lib/python3.6/site-packages/tda/auth.py", line 55, in load
    with open(token_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'token.pickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rod/Projects/tda/venv/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 17, in <module>
    with webdriver.Chrome() as driver:
  File "/home/rod/Projects/tda/venv/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/rod/Projects/tda/venv/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


```

**Comment by alexgolec** [comment]
This looks like an issue with your chromedriver installation. Closing for now, but feel free to comment with a reason why you think this is an issue with `tda-api` library code.

**Comment by spitzbubchen** [comment]
Yes, it was. Thanks for the quick response. Resolved it with:

`sudo apt-get install chromium-chromedriver`
