### ISSUE TITLE
False assumption that place_order returns JSON

### ISSUE THREAD

**Issue by nicmcd** [alexgolec/tda-api#65]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
The place_orders function falsely assumes that JSON is returned. This previously was not a concern but the addition of logging now causes a problem.
Here is the problem line: 
https://github.com/alexgolec/tda-api/blob/6ccac2eed8051026a7472032f69f51a6f27ef20b/tda/debug.py#L54
`place_order()` calls `__post_request()` which calls the problem function:
https://github.com/alexgolec/tda-api/blob/6ccac2eed8051026a7472032f69f51a6f27ef20b/tda/client.py#L311
https://github.com/alexgolec/tda-api/blob/6ccac2eed8051026a7472032f69f51a6f27ef20b/tda/client.py#L122

**Code to Reproduce**
Any call to place_order should cause this problem. 

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
Not crash

**Actual Behavior**
Crash

**Error/Exception Log, If Applicable**
Here is a log from my execution:

```
[debug.py:150:_enable_bug_report_logging] tda-api version 0.6.1
[client.py:118:__post_request] Req 1: POST to https://api.tdameritrade.com/v1/accounts/BLAHBLAH/orders, json={
    "orderType": "MARKET",
    "session": "NORMAL",
    "duration": "DAY",
    "orderStrategyType": "SINGLE",
    "orderLegCollection": [
        {
            "instruction": "BUY",
            "quantity": 2,
            "instrument": {
                "symbol": "HEXO",
                "assetType": "EQUITY"
            }
        }
    ]
}
[auth.py:20:update_token] Updating token to file /home/nic/token.pickle
[client.py:55:__log_response] Req 1: GET response: 201, content=
```

**Comment by nicmcd** [comment]
Presumably the right fix is to add a check in `register_redactions_from_response()` for JSON content before attempting to parse JSON content.

**Comment by nicmcd** [comment]
The code in debug.py has a try/except block to catch the error. However, my execution gave this error:

```
Traceback (most recent call last):
  File "/home/nic/.cache/bazel/_bazel_nic/27747ef8418c957df83c1f6e8d19ec81/execroot/__main__/bazel-out/k8-opt/bin/trade/buy.runfiles/__main__/trade/buy.py", line 157, in <module>
    main(args)
  File "/home/nic/.cache/bazel/_bazel_nic/27747ef8418c957df83c1f6e8d19ec81/execroot/__main__/bazel-out/k8-opt/bin/trade/buy.runfiles/__main__/trade/buy.py", line 76, in main
    resp = kit.client.place_order(
  File "/home/nic/.local/lib/python3.8/site-packages/tda_api-0.6.1-py3.8.egg/tda/client.py", line 315, in place_order
  File "/home/nic/.local/lib/python3.8/site-packages/tda_api-0.6.1-py3.8.egg/tda/client.py", line 123, in __post_request
  File "/home/nic/.local/lib/python3.8/site-packages/tda_api-0.6.1-py3.8.egg/tda/debug.py", line 54, in register_redactions_from_response
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The code try to catch `json.errors.JSONDecodeError` by instead a `simplejson.errors.JSONDecodeError` is raised.

**Comment by nicmcd** [comment]
If I replace `json.errors.JSONDecodeError` in debug.py with ValueError, my code works completely.

For what it is worth, I'm using Python 3.8.2 on Ubuntu 20.04.

**Comment by alexgolec** [comment]
Just so I understand, can you show the actual exception stack trace that comes out of this failure?

**Comment by nicmcd** [comment]
That is in my second comment above, right?

**Comment by alexgolec** [comment]
Aaah, sorry, I misread that, you're right. I'll add more comments to your PR.
