### ISSUE TITLE
StreamingClient: websockets.exceptions.ConnectionClosedOK

### ISSUE THREAD

**Issue by jmy48** [alexgolec/tda-api#82]
I've made a TDA brokerage and API account, and running this block of code
```
client = auth.client_from_token_file(token_path, api_key)
stream_client = StreamClient(client, account_id=api_key)

async def read_stream():
    await stream_client.login()
    await stream_client.quality_of_service(StreamClient.QOSLevel.EXPRESS)
    await stream_client.nasdaq_book_subs(['GOOG'])
    stream_client.add_timesale_options_handler(
            lambda msg: print(json.dumps(msg, indent=4)))

    while True:
        await stream_client.handle_message()

asyncio.get_event_loop().run_until_complete(read_stream())
```

produces:
```
Traceback (most recent call last):
  File "store.py", line 40, in <module>
    asyncio.get_event_loop().run_until_complete(read_stream())
  File "/Users/Joshua/anaconda3/envs/tda/lib/python3.8/asyncio/base_events.py", line 616, in run_unti
l_complete
    return future.result()
  File "store.py", line 31, in read_stream
    await stream_client.login()
  File "/Users/Joshua/anaconda3/envs/tda/lib/python3.8/site-packages/tda/streaming.py", line 365, in
login
    await self._await_response(request_id, 'ADMIN', 'LOGIN')
  File "/Users/Joshua/anaconda3/envs/tda/lib/python3.8/site-packages/tda/streaming.py", line 229, in
_await_response
    resp = await self._receive()
  File "/Users/Joshua/anaconda3/envs/tda/lib/python3.8/site-packages/tda/streaming.py", line 140, in
_receive
    raw = await self._socket.recv()
  File "/Users/Joshua/anaconda3/envs/tda/lib/python3.8/site-packages/websockets/protocol.py", line 50
9, in recv
    await self.ensure_open()
  File "/Users/Joshua/anaconda3/envs/tda/lib/python3.8/site-packages/websockets/protocol.py", line 81
2, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), no reason
```

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for help requests. Feel free to join our discord to ask questions: 

https://discord.gg/M3vjtHj
